name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add SSH key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 34.201.50.95 >> ~/.ssh/known_hosts

      - name: Setup SSH key
        run: |
          echo "${{secrets.DEPLOY_KEY}}" > deploy_key
          chmod 600 deploy_key
          eval $(ssh-agent -s)
          ssh-add deploy_key
        shell: /usr/bin/bash -e {0}

      - name: Deploy to VPS
        run: |
          ssh ubuntu@34.201.50.95 "cd /var/repo/meusite.git && git --work-tree=/var/www/meusite --git-dir=/var/repo/meusite.git checkout -f"
